### PR TITLE
Support for xhr timeout

### PR DESCRIPTION
**Pull request by ErikLarsson82**
Pull request connected to issue 480.

https://github.com/rendrjs/rendr/issues/480

### CODE REVIEW

**Comment by saponifi3d** [comment]
oooo i like this! Would you mind adding a quick test for the case where there is a timeout and where there it uses the default `0`?

**Comment by ErikLarsson82** [comment]
@saponifi3d I added the tests you requested :)

**Comment by pjanuario** [comment]
:+1:

**Comment by saponifi3d** [comment]
Awesome looks great!!

**Comment by ErikLarsson82** [comment]
=^_^=

**Pull request merged**
