### PR TITLE
Fixes fetchFromApi to work in amd (async) environments

### PR DESCRIPTION
**Pull request by alexindigo**
Fixing another integration point with AMD universe. Thanks.

/cc @rendrjs/maintainers @crwang

### CODE REVIEW

**Comment by spikebrehm** [comment]
LGTM, thanks.

**Comment by alexindigo** [comment]
Thank you @spikebrehm. Any ETA on new package cut? :)

**Comment by spikebrehm** [comment]
That's a better question for the rest of @rendrjs/maintainers  :)

**Comment by alexindigo** [comment]
I see. Thanks.

@rendrjs/maintainers let me know if I can help in any way to expedite the process. Thanks.

**Comment by saponifi3d** [comment]
@alexindigo I can cut aa minor release tonight or tomorrow. Doesn't look like this is anything more than a bug fix

**Comment by alexindigo** [comment]
Yep, just a bug fix. `fetchFromApi` is async anyway, this one just makes it true to it's nature. :)
Thanks.

**Pull request merged**
