### PR TITLE
Call the controller method with the right context

### PR DESCRIPTION
**Pull request by purusho**
- The controller was called with the wrong context.
- Some variable changes
- Added unit test 
- Unit test code cleanup

### CODE REVIEW

**Comment by purusho** [comment]
@rendrjs/maintainers any update on merging this PR ?

**Comment by alexindigo** [comment]
@rendrjs/maintainers Is there anything missing from this PR that prevents it from merging? We'd like to go ahead with our changes. Thank you.

**Comment by saponifi3d** [comment]
:+1: sorry didn't see this PR.

**Comment by saponifi3d** [comment]
@alexindigo @purusho fyi - i just released version 1.0.2 which includes these changes (and the other PRs you've made) :dancers: thanks for all the work on it!

**Comment by alexindigo** [comment]
Thank you.

**Pull request merged**
